# Generated by Django 6.0.2 on 2026-03-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsapp', '0002_dailyqr_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyQR',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
