# Generated by Django 6.0.2 on 2026-03-24 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsapp', '0003_delete_dailyqr_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='qr_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
