# Generated by Django 6.0.2 on 2026-03-25 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsapp', '0004_attendance_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='qr_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
