# Generated by Django 6.0.2 on 2026-03-25 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsapp', '0005_alter_attendance_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
