# Generated by Django 6.0.2 on 2026-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(max_length=100)),
                ('dpt_des', models.TextField(max_length=1000)),
                ('dpt_phone', models.TextField(max_length=100)),
                ('dpt_email', models.EmailField(max_length=100)),
                ('dpt_image', models.ImageField(blank=True, null=True, upload_to='departments/')),
            ],
        ),
    ]
