# Generated by Django 6.0.2 on 2026-03-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctordb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100, unique=True)),
                ('doc_dpt', models.TextField(max_length=1000)),
                ('doc_phone', models.TextField(max_length=10)),
                ('doc_email', models.EmailField(max_length=100)),
                ('doc_image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
            ],
        ),
        migrations.AlterField(
            model_name='departmentdb',
            name='dpt_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='departmentdb',
            name='dpt_phone',
            field=models.TextField(max_length=10),
        ),
    ]
