# Generated by Django 6.0.2 on 2026-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_doctordb_alter_departmentdb_dpt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='doc_quali',
            field=models.TextField(default='MBBS', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctordb',
            name='doc_phone',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
