# Generated by Django 6.0.2 on 2026-03-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_doctordb_doc_quali_alter_doctordb_doc_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordb',
            name='doc_name',
            field=models.CharField(max_length=100),
        ),
    ]
