# Generated by Django 6.0.2 on 2026-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.TextField(max_length=100)),
                ('doctor', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
